on:
# Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
    
  # Allow manual triggering of the workflow
  workflow_dispatch:
  
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Generate the Pacman contribution animation
      - name: Generate GitHub Contributions Pacman Animation
        uses: Platane/snk@v3
        with:
          # GitHub username
          github_user_name: ${{ github.repository_owner }}
          
          # Custom SVG outputs with Pacman theme
          outputs: |
            dist/github-pacman.svg
            dist/github-pacman-dark.svg?palette=github-dark&color_dots=#2ea043,#006d32,#39d353&color_snake=#ffff00
            dist/pacman.gif?color_snake=#ffff00&color_dots=#2ea043,#006d32,#39d353

          # Custom configuration for Pacman appearance
          settings: |
            {
              "character_design": "pacman",
              "animation_duration": 1.5,
              "movement_style": "chase",
              "ghost_colors": ["#ff0000", "#00ffff", "#ff69b4", "#ffa500"]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Deploy to output branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update Pacman contribution animation [skip ci]"
